# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :prepare do

    # checkout release branch
    #ensure_git_status_clean

    # clear data
    clear_derived_data
    xcclean(
        scheme: "OnlineStore",
        workspace: "OnlineStore.xcworkspace"
    )

    # update a dependencies
    cocoapods(
        use_bundle_exec: false
    )
  end

  lane :full_tests do
   prepare

   # run tests
   run_tests

   # make screenshots
   capture_ios_screenshots
  end
end
